### ISSUE TITLE
Losing Captcha Settings & Text on Submission Button on Update

### ISSUE THREAD

**Issue by The-Dan-Main** [solspace/craft3-freeform#1098]
**Describe the bug or issue you're experiencing**

I am currently updating many of my craft CMS Websites with Freeform Plugin and when i upgrade from v4 to v5 (freeform), it loses my integration of all Captchas and as well the text on my submission buttons. (it gets reset to "submit").

This happened now on all of my 12 craft instances, which i updated already.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.5.2 
- Freeform Version: 4.1.6
- Freeform Edition:  Pro
- Fresh Install or Upgrade: Fresh install

**Comment by kjmartens** [comment]
Sorry for the trouble @The-Dan-Main.

The migration does not migrate everything because some things are quite a bit different from v4 to v5. For example, the reCAPTCHA integration is now handled as a Captcha integration type where multiple can be configured and applied to forms. Submit buttons are now automatically loaded into the page instead of stored as a special field type inside the layout. It's possible the migration could choke if there were more than 1 submit button in the same page, etc.
