### ISSUE TITLE
Javascript Error when using conditionally shown/hidden HTML-Elements

### ISSUE THREAD

**Issue by jtschulik-pcweb** [solspace/craft3-freeform#1110]
**Describe the bug or issue you're experiencing**
Getting a Javascript-Error:
`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '[data-field-container=1BNoEp2GN]' is not a valid selector.`
When using a Form with HTML-Elements that are conditionally shown/hidden.
It seems to me that the Error is causing other Elements to not function properly anymore (Datepicker, Elements that should be hidden by default are shown...)

**Steps to reproduce**

1. Create a Form with HTML-Elements that are conditionally shown by checkbox values
2. View the Form in Frontend
3. Open Devtools Console

**Expected behavior**
Conditionally show/hidden Elements are show/hidden as expected without JS-Errors

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.0
- Freeform Version: 5.1.0
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
HTML Entries have "random" IDs/Strings as data-field-container values, when these values are starting with a number (e.g. "1BNoEp2GN"), the JS Error occurs.
It seems this is because
`document.querySelector("[data-field-container=".concat(r, "]"));`
in plugin.js is missing quotes
When setting the quotes via devtools, the rror disappears

**Comment by kjmartens** [comment]
Sorry about this @jtschulik-pcweb,

You're right that the issue happens when a handle begins with a number. In Freeform 4, special fields like HTML blocks didn't have true handles, so they were assigned a random hash, sometimes beginning with a number. The migration process recreates these HTML blocks in the form layout and assigns them an actual handle that matches.

In Freeform 5, we changed how Conditional Rules work on the front end, so I can see how this is a problem now. We'll make an adjustment to account for this in an upcoming release.

In the meantime, you can of course get around this by renaming that HTML field handle in the builder. 🙂

**Comment by jtschulik-pcweb** [comment]
Thank you @kjmartens !
