### ISSUE TITLE
1068 Multiple primary key defined error when installing

### ISSUE THREAD

**Issue by atelierbim** [solspace/craft3-freeform#1171]
An error occurred while executing the "Solspace\Freeform\migrations\Install migration: SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined
The SQL being executed was: ALTER TABLE `freeform_rules_fields` ADD CONSTRAINT `PRIMARY_KEY` PRIMARY KEY (`id`)

**Steps to reproduce**

1. Unistall freeform
2. Install freeform

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.6
- Freeform Version: 5.1
- Freeform Edition: PRO
- Fresh Install or Upgrade: upgrade

**Additional context**

**Comment by kjmartens** [comment]
Sorry for the delay and the trouble, @atelierbim 

Were you able to figure this one out already? I am not able to duplicate this issue.

My best guess is that the install or uninstall (or migration from v4) got corrupted or choked somewhere along the way, leaving some broken database table data. Can you elaborate on what might have happened, which version you came from (if upgrading), and which exact version you attempted to update to / install.

And finally, before you attempt to install Freeform, are you seeing any `freeform_` database tables left in the database? 🙂

**Comment by atelierbim** [comment]
Hi,
Yes I solved it by totally uninstalling the plugin, delete the Freeform DB tables and start from scratch...
Thank for the help anyway,

Jeremy Mathez

**Comment by elivz** [comment]
I am running into this same error when upgrading from v4 to v5, and I believe I have tracked it down to MySQL's [sql_generate_invisible_primary_key](https://dev.mysql.com/doc/refman/8.0/en/create-table-gipks.html) setting. A short term fix seems to be to just disable that setting, but I _think_ you could handle the situation by setting `id => $this->primaryKey()` when the table is created, rather that adding the key in a second step. The issue right now is that MySQL automatically creates a hidden PK (`my_row_id`) when the table is created, and then setting `id` as the primary fails because there is already a PK at that point and you can't have two.

**Comment by kjmartens** [comment]
Thanks @elivz.

We'll have a developer take a look. 🙂 

Are you able to include a screenshot of your Freeform Diagnostics page?
