### ISSUE TITLE
Honeypot check failed

### ISSUE THREAD

**Issue by sandissauka** [solspace/craft3-freeform#129]
We've noticed that all the form submits are going to the spam folder with the mark "Honeypot check failed". These are all legit. 

We've checked into the code and it looks like the web side is not filling in the field Freeform is generating. We've deactivated "Javascript Enhancement" temporarily and now it doesn't fall into the spam.

We're using the latest Freeform 3.10.11

**Comment by gustavs-gutmanis** [comment]
@sandissauka thanks for reporting this.  
Does it work on your machine, when you have the enhanced honeypot enabled? Maybe the client that submitted the form has his JS disabled?

**Comment by sandissauka** [comment]
possible, but not likely – around 20 legit submits,

**Comment by gustavs-gutmanis** [comment]
Can you please try it out locally, see if the problem persists?

Which version of Freeform are you running on?

**Comment by kjmartens** [comment]
@sandissauka Are you caching the form? If so, you'll need to make sure you're manually refreshing the Honeypot token:
https://docs.solspace.com/craft/freeform/v3/templating/caching.html

**Comment by sandissauka** [comment]
@gustavs-gutmanis I've mentioned originally, we're using the latest version: Freeform 3.10.11. Sorry, I didn't mention we already tested locally. Both: locally and live works only when "Javascript Enhancement" is switched off. 

@kjmartens we do use cache site-wide except pages with the form.

**Comment by gustavs-gutmanis** [comment]
Sorry @sandissauka, I missed the fact that you specified the version.

This sounds like a caching problem, even though you say you're not caching the form page.  
Could you open up the browser dev tools and check if the honeypot input field gets updated values for each separate request (refreshing the page should yield different values each time)?

If the values are never updated, then it's a caching issue.

**Comment by raitisg** [comment]
I'm in the same team as @sandissauka and can provide some details.

Cache is not an issue - at least not with the plugin we are using (we've disabled it completely during tests).

Honeypot value is different every time form/page is refreshed. We are setting it using code from official docs: https://docs.solspace.com/craft/freeform/v3/templating/caching.html#twig-template-caching
Without this JS, input field is always empty.

Simplified, our form looks ilke this:

```
{{ form.renderTag() }}

{% for row in form %}
	{% for field in row %}
		{{ field.render(...) }}
	{% endfor %}
{% endfor %}

{{ form.renderClosingTag }}

<script>
	// Get a fresh Honeypot via `craft.freeform.honeypot()` service
	const honeypot = JSON.parse('{{ craft.freeform.honeypot(form)|json_encode|raw }}');

	// Find the corresponding Form
	const form = document.querySelector('form[data-handle=\'{{ form.handle }}\']');

	// Locate and update the Hash input
	const formHashInput = form.querySelector('input[name=formHash]');
	formHashInput.setAttribute('value', '{{ form.hash }}');

	// Locate and update the Honeypot input
	const honeypotInput = form.querySelector('input[name^="freeform_form_handle"]');
	honeypotInput.setAttribute('id', honeypot.name);
	honeypotInput.setAttribute('name', honeypot.name);
	honeypotInput.value = honeypot.hash;

	// Locate and update the CSRF input
	const csrfInput = form.querySelector('input[name={{ craft.app.config.general.csrfTokenName|e('js') }}]');
	csrfInput.value = '{{ craft.app.request.csrfToken|e('js') }}';
</script>
```

**Comment by gustavs-gutmanis** [comment]
Thanks @raitisg,  
I will try to reproduce this issue, but from what it looks like right now - it seems like the generated honeypot isn't stored in the session. Do you have anything extra added to the default PHP stack? Any load balancers or something like that on the server? How are the sessions stored?

**Comment by gustavs-gutmanis** [comment]
I can't reproduce the issue, but if you're not caching the form at all, then you don't need to manually set up the honeypot and csrf inputs.

If you are caching the form, then make sure you're only caching the rendering part, not the part where you fetch and set the form variable.

You could do some additional debugging in `\Solspace\Freeform\Services\HoneypotService::validateFormHoneypot` method, which is on line `65`. See if the `$honeypotList` on line `87` contains anything at all.

**Comment by raitisg** [comment]
@gustavs-gutmanis Thanks for your reply. I did some debugging and these are my conclusions:

- `validateFormHoneypot` checks honeypot hash (9 characters long) against form value (6 characters long). This is the reason it fails.
- JS example in docs is correct: `honeypotInput.value = honeypot.hash` indeed sets correct value (_hash_) on page load, but upon submitting, some other JS file changes that to (incorrect) _value_ again. 

We are using Vue to submit our form. Code is very simple, it should not interfere with your JS, but I'm probably missing something since it works on your end and other users are not complaining.

I've moved `honeypotInput.value = honeypot.hash` code to Vue just before form submission and it now works. I guess this can be closed now.

**Comment by gustavs-gutmanis** [comment]
In Freeform 3.10 the honeypot starts with a random value, but gets set to the correct one once the page is loaded, via a javascript line which gets added along with the rest of the form scripts.

In Freeform 3.11 this functionality has been consolidated into the freeform plugin JS file and its values are added to the form tag via the `data-` attributes, which would help more in this case, since you're using Vue. It is possible to disable the original freeform scripts and run just on Vue.

Glad you got it working for you, though!
