### ISSUE TITLE
ReCaptcha environment variables parsing not working

### ISSUE THREAD

**Issue by valboivin** [solspace/craft3-freeform#1392]
### What happened?

We often have to upsync our database from one environment to another one. However, everytime we do so, we lose the values of our ReCaptcha Site Key and Secret Key in our Captchas settings. We use environment variables to set them in the CMS. 

If I look into the database, I can see that the `siteKey` and `secret key` values (not the variables keys) are there in the metadata column of our captchas integration row in the `freeform_integrations` table. 

I'm wondering if there's an issue with parsing the value to find the corresponding environment variable.

(We've never had this problem while we were using the Freeform 4 version.) 

![Screenshot 2024-07-02 at 2 15 40 PM](https://github.com/solspace/craft-freeform/assets/27648426/82608223-3c96-4cac-a000-a3787a4f85a0)

![Screenshot 2024-07-02 at 2 15 52 PM](https://github.com/solspace/craft-freeform/assets/27648426/575d63da-e37d-4b30-8c3d-2a554d93ebd0)

<img width="757" alt="Screenshot 2024-07-02 at 2 16 08 PM" src="https://github.com/solspace/craft-freeform/assets/27648426/bbbfa450-16b1-46c9-99c6-42f3ef7118db">

### How can we reproduce this?

1. Set the ReCaptcha Site Key and Secret Key with an environment variable 
2. Export the database, and reimport it
3. Site Key and Secret Key are now empty in the CMS

### Freeform Edition

Pro

### Freeform Version

5.5.1

### Craft Version

4.10.2

### When did this issue start?

After upgrading from older Craft version

**Comment by gustavs-gutmanis** [comment]
Hi @valboivin,

The reason for this is that the `CRAFT_SECURITY_KEY` in your `.env` file differs between the environments.

All the sensitive data in the database is encrypted so that if anyone gains access to your database, they would not be able to do API calls to your integrations leaking or destroying data.

This does encrypt env variables as well, but we could make it so that if env variables are used, they are not encrypted. That would make a lot of sense. But meanwhile, you will have to re-enter those, unfortunately.

Thanks for reporting this though, we're adding this to our feature list :)

**Comment by kjmartens** [comment]
This feature has now been added to Freeform 5.5.3. 🙂

**Comment by valboivin** [comment]
Thank you so much! It works. 🙂
