### ISSUE TITLE
URGENT: Ran craft update and it collapsed production (after working locally)

### ISSUE THREAD

**Issue by JayBox325** [solspace/craft3-freeform#1403]
### What happened?

I locally ran ./craft update and updated Freeform from 4.1 to 5.5. Worked locally, pushed up, and it killed my production sites. I have tried to revert the local version back to Freeform 4.1 and now that is erroring too.

Please, any one to one support would be phenomenal as this happened due to an initial error on the production sites:

```
Solspace\Freeform\Services\FormsService::EVENT_ATTACH_FORM_ATTRIBUTES
```

Which is nothing I'd have touched. But since attempting to revert versions and downgrading back, I am now getting this error on production:

```
PHP Fatal Error – [yii\base\ErrorException](https://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)
Class Solspace\Freeform\Bundles\Form\Types\Surveys\Survey contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Solspace\Freeform\Library\FormTypes\FormTypeInterface::getTypeName, Solspace\Freeform\Library\FormTypes\FormTypeInterface::getPropertyManifest, Solspace\Freeform\Library\FormTypes\FormTypeInterface::getMetadata)
```

And this error locally (albeit with an out of date database content wise):

```
Database Exception – [yii\db\Exception](https://www.yiiframework.com/doc-2.0/yii-db-exception.html)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'forms.submissionTitleFormat' in 'field list'
The SQL being executed was: SELECT `forms`.`id`, `forms`.`type`, `forms`.`metadata`, `forms`.`uid`, `forms`.`name`, `forms`.`handle`, `forms`.`spamBlockCount`, `forms`.`submissionTitleFormat`, `forms`.`description`, `forms`.`layoutJson`, `forms`.`returnUrl`, `forms`.`defaultStatus`, `forms`.`formTemplateId`, `forms`.`color`
FROM `freeform_forms` `forms`
ORDER BY `forms`.`order`, `forms`.`name`
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'forms.submissionTitleFormat' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'forms.submissionTitleFormat' in 'field list'
in /var/www/html/vendor/yiisoft/yii2/db/Command.php at line 1302
```

At this point, I need urgent support to get the sites back up and running so I don't lose the content from my client (especially the form submissions) then resolve, reset and stabilise the project after.

### How can we reproduce this?

1. Successfully run Freeform 4.1 on Craft 4.6
2. Run `./craft update` to go to Freeform 5.5.2 and Craft 4.10
3. See how it's then broken without warning.

### Freeform Edition

Pro

### Freeform Version

5.5

### Craft Version

4.10

### When did this issue start?

After upgrading from older Freeform version

### Previous Freeform Version

4.1

**Comment by kjmartens** [comment]
Hi @JayBox325,

I'm very sorry to hear about the trouble you're experiencing with updating Freeform.

**Do you have a backup you can use to revert your site? That would be wise to do now as resolving this issue likely won't be very fast. The secondary issue you're experiencing is that your database has likely only partially been restored when you rolled back. If you don't have a backup to restore, can you try using your local dev database with Freeform 5.x again to get back to the original error? That will likely be much easier to work backward from.**

I have several questions to ask to help clarify the situation:

1. Which exact version of Freeform 4.x did you upgrade from?
2. Did or do you have the Freeform Surveys & Polls plugin installed?
3. After you updated locally, did you perform the cleanup tasks (as noted in the [Freeform 4 Update guide](https://docs.solspace.com/craft/freeform/v5/setup/updating-freeform-4/)) and thoroughly test Freeform 5.x on the site to ensure it worked correctly? The update process from Freeform 4 to 5 is substantial since 5.x is a major overhaul. The migration will handle a lot of it, but some things will need to be adjusted in your forms, integrations, settings, and templates. You can see that guide here: https://docs.solspace.com/craft/freeform/v5/setup/updating-freeform-4/
4. Did the migration part appear to work correctly and completely? I assume this was done via CLI (and not the CP)?
5. At which point did you get this error? `Solspace\Freeform\Services\FormsService::EVENT_ATTACH_FORM_ATTRIBUTES` And do you have any other context around it? Where exactly did you see it, what did the error say, and was there a stack trace available for it? Something might be stored in the Craft logs still, if you want to try searching for it.

Thanks 🙂
