### ISSUE TITLE
Dutch translations are weird

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [solspace/craft3-freeform#1407]
### What happened?

Hi we noticed the dutch translations have been changed and they are a bit odd.
For example the save button  (top right of form edit)says Redden which is more like to rescue something or someone it has nothing to do with saving a document. It should be "Opslaan". Also after clicking it it says besparing which means to save money or fuel or something but not a document.

### How can we reproduce this?

1. 
2. 
3. 

### Freeform Edition

Pro

### Freeform Version

5.5.1

### Craft Version

4.10.3

**Comment by kjmartens** [comment]
Sorry about this @bob-pixeldeluxe 

Due to a very large number of setting and wording changes in Freeform 5, for a starting point we used Google Translate.

Would you be willing to have a look at the NL translation file and submit a PR? It's quite large though, so I'm not sure if you would have time for that. Otherwise, is there maybe a top 10 or so list of bad translations you could help us out with fixing? 🙂 

Thanks!

**Comment by bob-pixeldeluxe** [comment]
Hi, no problem it seems google translate does not understand Dutch very wel ;).
I dont have time to read through it all but most of it seems fine here are the weird ones I noticed while using freeform: 
(https://github.com/solspace/craft-freeform/compare/v5...bob-pixeldeluxe:craft-freeform:patch-1)

**Comment by kjmartens** [comment]
Thank you very much for this @bob-pixeldeluxe. We'll update this for the next release. 🙂
