### ISSUE TITLE
Honeypot Check Failing for every form submission

### ISSUE THREAD

**Issue by jlapan** [solspace/craft3-freeform#185]
**Describe the bug or issue you're experiencing**
Similar to issue #129, our form submissions honeypot check is failing which is sending all submissions into our spam folder. I have several other Craft sites that use this same plugin with no issues so I am not sure why my current site is behaving differently. I have configured all the sites in the same manner. Also, there is no caching happening on my form.

**Steps to reproduce**

1. Enable the enhanced javascript feature
2. Submit form

**Expected behavior**
Legit form submissions to not go into the spam folder.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.7
- Freeform Version: 3.11.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @jlapan, can you confirm a few things?

1. When the enhanced javascript setting is disabled, does everything work correctly?
2. Are 100% of the submissions going to spam when the setting is enabled?
3. Can you try loading the form inside the Bootstrap area of the [Demo Templates](https://docs.solspace.com/craft/freeform/v3/setup/demo-templates.html)? Does it work correctly there?
4. Which version of Freeform did you upgrade from?

Thanks! :)

**Comment by jlapan** [comment]
Hey @kjmartens, to confirm:

1. Yes, when enhanced javascript is disabled, everything works. However, we receive so much spam that the honey pot feature doesn't catch. Enabling the enhanced javascript feature fixed this issue for us.
2. When enabled, yes, it appears as if 100% are going to spam folder. However, now a weird behavior is happening where the form will simulate a successful submission, redirect to the success page, but no record of the form submission is found in the spam folder or in the submissions area. It's not even recording the form submission.
3. I used the demo templates with enhanced javascript enabled and disabled...both worked properly. Wondering then if something is wrong with how I am using the form on my templates...
4. I just upgraded from 3.11.9, but I believe this issue started after upgraded from 3.10.10

**Comment by kjmartens** [comment]
In the general settings for Freeform, what do you have set for the "Freeform Script Insert Type" setting?  If it is set to **As Static URLs** and you have server rules applied to scripts, it might be failing there. Can you instead try switching it to **As Files**? :)

**Comment by jlapan** [comment]
@kjmartens I have tried to switch this setting and have not had any luck...

**Comment by kjmartens** [comment]
@jlapan my best guess here, given the results you mention in the previous comment and your latest one would indicate there's probably some kind of caching happening on the page the form is in. It seems like a textbook case for it since we ruled out the other possibilities.

Just to recap:

1. You say the form works perfectly fine with or without JS enhancement inside the demo templates? The demo templates are typically isolated from whatever you're doing in other areas of your website. Perhaps you have some kind of special validation or some other unrelated script(s) for the site that are interfering with Freeform. We've seen this as well. If you have the "Freeform Script Insertion Location" setting set to "Page Footer", then you'll also want to make sure the page the form is on contains a closing `</body>` tag, etc, as Freeform will then look for that and apply its scripts there (or you can switch the setting to "Inside Form").
2. You say that the issue happens in both As Static URLs and As Files options for the "Freeform Script Insert Type" setting? This would rule out there being server rules applied to scripts, etc.
3. You say the form works perfectly fine in your own templates without JS enhancement, but fails with it enabled. If the page has some kind of caching (cache tags, plugin-based caching, server-level caching, etc), the JS enhancement will absolutely not work UNLESS the token is manually refreshed. However, the Craft CSRF token would need to be refresh as well (and perhaps that is already happening somehow on your site). See [Cacheable Forms documentation](https://docs.solspace.com/craft/freeform/v3/templating/caching.html) for more info.

Of the thousands upon thousands of websites using Freeform, a failure like the one you're experiencing always falls into one of the categories above. 🙂
