### ISSUE TITLE
Hubspot integration not accounting for Hubspot property names containing double underscores

### ISSUE THREAD

**Issue by simple-nicholas** [solspace/craft3-freeform#204]
**Describe the bug or issue you're experiencing**
Hubspot integration doesn't properly account for Hubspot fields with double underscores in the property name (eg the label "Questions / Comments" gives the property name "questions__comments")

**Steps to reproduce**
1. Create a property in Hubspot with a name containing double underscores
2. Create a form with a Hubspot integration and map a form field to that Hubspot property
3. Submit the form and check what appears in Hubspot

**Expected behavior**
Field mapping/Integration should work as normal for Hubspot property nameds containing double underscores

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.13 (Same issue on earlier versions)
- Freeform Version: 3.11.11 (Same issue on earlier versions)
- Freeform Edition: Pro
- Fresh Install or Upgrade: Fresh

**Additional context**

**Comment by gustavs-gutmanis** [comment]
Hi @simple-nicholas,
We're very sorry, but having two consecutive underscores is handled by Freeform as a special case, because of a patched in functionality to support field groups which weren't supported on the initial launch of Freeform integrations.  
Is it possible for you to avoid generating a two underscore handle for the field?  
This is a larger refactor which we haven't currently scheduled.
