### ISSUE TITLE
reCaptcha V3 not adding needed scripts

### ISSUE THREAD

**Issue by knynkwl** [solspace/craft3-freeform#206]
**Describe the bug or issue you're experiencing**
I enabled reCaptcha, added the Necessary keys but when I go to the form, and inspect the dom, there is nothiing related to reCaptcha.

The only thing I see in the DOM related is it freeform adds the data attributes to the form.

```
data-recaptcha="v3"
data-recaptcha-key="*****"
data-recaptcha-action="homepage"
```

But other than those data attributes, nothing else in the dom is related to recapchta. 

**Steps to reproduce**

1. Enable Recaptcha V3

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft CMS 3.7.5
- Freeform Version: 3.11.10
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
@knynkwl Are you seeing a reCAPTCHA logo at the bottom right corner of the page? If so, it's working and nothing else needs to happen with **v3**. reCAPTCHA v2 Checkbox is the one that displays a checkbox for the user to interact with. :)

**Comment by knynkwl** [comment]
@kjmartens nope, there was no recaptcha icon or any other indication it was working.

**Comment by kjmartens** [comment]
@knynkwl If you try loading this inside the Bootstrap area of the [demo templates](https://docs.solspace.com/craft/freeform/v3/setup/demo-templates.html) included with Freeform, does the issue still happen?

If it doesn't work there, can you also include a screenshot of the reCAPTCHA settings page (with tokens blurred or whatever?

**Comment by dellanesta** [comment]
@knynkwl Hi, i have your issue; have you resolved it?

**Comment by kjmartens** [comment]
Hi @dellanesta,

Can you share what your setup is like? Perhaps a screenshot of the Diagnostics page? 🙂

**Comment by dellanesta** [comment]
Hi @kjmartens 

**Steps to reproduce**
Enable Recaptcha V3

**Craft & Plugin Info (please complete the following information):**
Craft Version: Craft CMS Pro 3.8.14
Freeform Version: 3.13.29
Freeform Edition: Pro
Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
@dellanesta, there are many other things in your setup that could contribute to this. I will need more information. The Diagnostics page is the easiest and quickest way to get most of that information. 🙂

**Comment by dellanesta** [comment]
Hi @kjmartens, looking at the freeform diagnostics I saw that I had set "Freeform Script Insertion Location" to "manual". I changed the setting to "on footer" and fixed it. Thanks anyway

**Comment by kjmartens** [comment]
Ok thanks. That would do it! 🙂

**Comment by ZJensenDev** [comment]
@kjmartens Hi! This has been happening for me recently on our site, I know this is closed but it seemed to have just dropped off because of people not responding rather than resolving. I've confirmed the other solutions listed in this thread are already in place.

**Describe the bug or issue you're experiencing**
On the live portion of the site freeform is not injecting recaptcha scripts. The recaptcha field is injected if you view source, and is recognized as it causes forms to not be able to submit. However theres no checkbox to click on to validate.

**Steps to reproduce**
1. Add V2 checkbox to form
2. Visit on live site

**Expected behavior**
Recaptcha appears where place in the form.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.6
- Freeform Version: 4.1.13
- Freeform Edition:  Pro
- Fresh Install or Upgrade: Upgrade

**Additional context**
The recaptcha works fine locally in a dev environment, on live previews everywhere, if I generate a link to a draft, and on other language versions of the site. It is only happening on the live main site.
