### ISSUE TITLE
On rare occurrence relation fails upon submit submission and does not update user's submissions form field

### ISSUE THREAD

**Issue by CAIDcreative** [solspace/craft3-freeform#213]
When a user submits a form it suppose to update a field on that user using relations (the field and user id is passed through via the relations parameter), 99% of the time this will work fine but on a rare occurrence the submission is submitted (it even creates an entry from the submission via element connection) but the field that stores what submissions the user submitted does not update. This has happened before once or twice, and a recent user had this happen 3 times in a row before it was successfully update.

**Steps to reproduce**

1. Have a user have a field to store user submissions
2. In the template under the 'relations' option pass in the field handle as the key and currentUser.id as the value
3. Submit Form

**Expected behavior**
If submission would be successful that field should always update

**Craft & Plugin Info (please complete the following information):**

- Craft Version: Craft Pro 3.7.16
- Freeform Version: 3.11.11.1
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by kjmartens** [comment]
Hi @CAIDcreative, is there any chance that the form is being left open on the page for a long time? It's very possible the PHP session is expiring before the user makes their additions/changes, and in edit mode, I believe the form might not be as obvious about that. The creation of the extra Craft entry actually somewhat confirms this because Freeform would treat the form as a new submission when it loses that context.

The Freeform 3.12 introduces additional ways to handle form sessions, including an encrypted payload which will be the new default for fresh installs (and existing ones can switch over to it of course). This will resolve this issue. It's in beta right now, but if you'd like to wait until later in the beta or after the beta, one workaround might simply be to include some kind of JS timer on the page that alerts the user that the session has expired and they should try again after refreshing the page.

**Comment by CAIDcreative** [comment]
I did a quick test of leaving my browser on for a long time and it sort of confirmed your suspicion: when I hit submit I was logged out of the user account immediately but it still submitted and created the entry but did not link it. If this will be fixed in 3.12 I think I'll wait for the official update, as even though this bug is annoying it happens at such a low frequency that it's the biggest issue to fix manually at the moment.

**Comment by kjmartens** [comment]
Just letting you know that Freeform 3.12 is now available. Just be sure to switch the **Freeform Session Context** setting from _PHP Sessions_ to _Encrypted Payload_. 🙂
