### ISSUE TITLE
Missing session context when sending AJAX form data (Headless/GraphQL)

### ISSUE THREAD

**Issue by karoljurczyk** [solspace/craft3-freeform#245]
**Describe the bug or issue you're experiencing**
I get `Form has expired` on first request when sending form built in Nuxt app (data fetched from GraphQL api endpoint)

**Steps to reproduce**
1. get form data and fields from GraphQL api endpoint
2. build custom form with all required fields from default template
3. send post request to `/actions/freeform/submit` with form data

**Expected behavior**
- adding session info to graphql interface is probably not a good idea, since graphlql queries are cached
- getting session context from separate endpoint - similar to getting csrf token from `/actions/users/session-info`
- option to either disable session context or create if empty

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.7.22
- Freeform Version: 3.12.6
- Freeform Edition: PRO

**Comment by gustavs-gutmanis** [comment]
Hi @karoljurczyk,

I would suggest following [this example](https://docs.solspace.com/craft/freeform/v3/templating/caching.html#static-page-caching-cdn-blitz) where you would create an endpoint that would provide you with the necessary tokens.

This approach is needed because you're able to modify the way any form works via templates, thus the custom form data is stored in a session and a unique hash is generated, and when the form is submitted, that data is then looked up and used for completing the form based on the parameters provided.

Freeform is meant to be used with freeform's JS plugin which handles many features and functionality that has to be controlled from the front-end, so when you use your own frameworks to generate the form, you're opting out of that functionality and have to provide your own.

Hope that link describes how to do what you're looking for. If not, please contact us again and we'll help out.

**Comment by karoljurczyk** [comment]
Thanks for quick response,

Yes, I saw that part of online docs and I will probably do something similar - problem is that when going headless You sort of opt out of twig templates :) and only use craft api endpoints.

I think for now I'll have to do some creative copy/paste (mostly involving SessionContext class) and use those methods in custom controller.

**Comment by gustavs-gutmanis** [comment]
If you can create your own endpoints, then you would be able to do something like this in the controller action:

```php
$formModel = Freeform::getInstance()->forms->getFormById(123);
$form = $formModel->getForm();
$form->registerContext();

return [
    'hash' => $form->getHash(),
];
```

You can pass all of the twig template render properties to the form via the `::registerContext()` action as an associative array as the first parameter.

**Comment by teamteak** [comment]
We were able to do this in our Next.js project but using the `/api` route to go backend to backend from next.js to Craft.  but now we are getting an error message that says `},
    data: { error: 'Unable to verify your data submission.' }` - which from the freeform docs is related to the csrf token. I have also verified that our config.php file has `sameSiteCookieValue => null`

**Comment by kjmartens** [comment]
@teamteak We've released 3.12.9, which I believe should resolve this issue. :)

**Comment by karoljurczyk** [comment]
btw. I ended up using custom endpoint which simply returns `$form->getForm()->json()` - it has both csrf and payload tokens amongst other info, so You can easily update Your form fields with them and successfully send form data to `/freeform/submit` endpoint

**Comment by teamteak** [comment]
> btw. I ended up using custom controller which simply returns `$form->getForm()->json()` - it has both csrf and payload tokens amongst other info, so You can easily update Your form fields with them and successfully send form data to `/freeform/submit` endpoint

@karoljurczyk  Would you mind posting your final solution?  Sounds like something we are working on as well.
