### ISSUE TITLE
Spam protection does not work

### ISSUE THREAD

**Issue by skramstad** [solspace/craft3-freeform#37]
Hi.

The spam filter does not work, every email sent with spam protection ON is identified as spam. How come?
No errors or debug info about this issue.

Craft 3
Freeform 2.0.0-beta.12

**Comment by kjmartens** [comment]
Hi @skramstad, would you be able to update to the latest version of Freeform (beta 14) first and see if the issue persists? And are you by chance testing without JS enabled? :)

**Comment by skramstad** [comment]
Hi @kjmartens , and I will test version 14 very soon. However we made a custom honeypot plugin for freeform that use a controller instead of javascript. So it should work even is javascript is disabled.
If I'm not mistaken, with javascript I guess a robot with javascript disabled will be able to spam right? If that is true, then the javascript version (freeform) is not something we will use in the future.

But I'll get back to you as soon as I've upgraded to version 14.

Cheers!

**Comment by skramstad** [comment]
Hi @kjmartens. Tested version 14 and still goes to spam. Javascript enabled. 

Are you considering recaptcha? https://github.com/solspace/craft3-freeform/issues/42

**Comment by kjmartens** [comment]
@skramstad we are making some big improvements to Spam protection for an upcoming release, and there will also be ReCaptcha availability for Freeform Pro, so yes. :)

As for your spam issue specifically, you've created your own spam plugin to tie into Freeform, so I imagine that's the issue here. We also don't provide any support for custom developed plugins unfortunately.

**Comment by skramstad** [comment]
@kjmartens That sound awesome. Looking forward to the update. If you need some beta testing just give me a heads up!

About the custom controller. Yeah we did that when Freeform failed. But when I tested version 14 I disabled our custom and enabled Freeform Spam filter. But it went straight to spam again.

**Comment by skramstad** [comment]
@kjmartens Do you know why every email goes to spam? Javascript enabled, including scripts in footer or inside the matrix block makes no difference. What sort of magic do you do to make it work?

**Comment by kjmartens** [comment]
Do you mean the form submission goes through and the actual email notifications work, but they go into your Spam folder in your email client, or do you mean something else?

**Comment by skramstad** [comment]
@kjmartens It's more like Freeform identifies it as spam. (The spam counter for the form in admin). So no warning or error when I submit. We dont use jQuery and javascript only. Is that a problem for Freeform spam filter?

**Comment by kjmartens** [comment]
It's hard to say what's happening when you're making your own custom plugin for Freeform to tie in. Ultimately, our current spam protection will block any submissions from browsers that are submitting the form without JS enabled, and/or if the hidden honeypot field value is edited. Freeform does not store any of the submitted data in this case, but will increment the spam counter.

We are now getting very close (days now) to releasing a new version of Freeform that will include a Spam folder option (so the spam goes to a folder rather than not recording data). The Pro edition will include reCAPTCHA. If that's what you're ultimately after, it'll be ready very soon. :)
