### ISSUE TITLE
Mailer Error in Control Panel

### ISSUE THREAD

**Issue by joshparylak** [solspace/craft3-freeform#491]
Form submissions create this error in the CP, with the type "Mailer service":
`Email "" does not comply with addr-spec of RFC 2822. {"template":"basic-notification","file":"/var/www/html/vendor/symfony/mime/Address.php"} []`

Seems to happen regardless of what email is submitted. If the email is a valid one, the form still processes correctly and all notifications send as expected.

Problem started around 10/19. We upgraded the site from Craft 3 to 4 in late September, so the error doesn't line up with that timing. Just brought site totally up-to-date to see if that solved the issue, but the problem remains.

**Steps to reproduce**

1. Submit Front end form
2. View error logs in Freeform Dashboard.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.1
- Freeform Version: 4.0.7
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade

**Comment by CAIDcreative** [comment]
I had a very similar problem after upgrade from craft 3 to 4. My issue turned out that in the email templates the "From Email" and "From Name" were calling craft variables via twig `{{ craft.app.systemSettings.getSettings('email').fromEmail }}` and `{{ craft.app.systemSettings.getSettings('email').fromName }}` but I guess they no longer work in craft 4 so was just sending out a blank string. I simply replaced them with environment variables I set $EMAIL_ADDRESS and $EMAIL_SENDER_NAME which fixed the issue.

**Comment by kjmartens** [comment]
Thanks @CAIDcreative. This is correct and likely the issue here. 🙂 

One other option is just to use `{{ craft.app.projectConfig.get('email.fromEmail') }}`, etc.

**Comment by jestov** [comment]
Hi, I recently upgraded freeform version from 3.11.11.1 to 4.0.8, after an upgrade from craft 3 to craft 4.

Days later these same issue began to happen:

` Email "" does not comply with addr-spec of RFC 2822. {"template":"distributedEmail","file":"/var/www/html/vendor/symfony/mime/Address.php"} []`

The only difference is that I'm calling the form as follows:

`{{ craft.freeform.form('cotizador',{ id: 'freeformCotizador' }).render() }}`

Any solution for this?

**Comment by kjmartens** [comment]
@jestov I have responded to your question here: https://github.com/solspace/craft-freeform/issues/572 🙂
