### ISSUE TITLE
A select form control with the " character in the <option> breaks the HTML and posts the default (first) value

### ISSUE THREAD

**Issue by lukehmu** [solspace/craft3-freeform#51]
They would ideally be escaped at a higher level than the template.

Example:
![image](https://user-images.githubusercontent.com/1893145/39431348-5d293aee-4c88-11e8-9554-7b0a26c9544d.png)

Temporarily fixed it by using a different character (″).

We're using your default `field.render()` function for selects.

It outputs something like:
`<option value="XS (38")">XS (38″)</option>`
As you can see, this leaves an unclosed ".

Thanks,
Luke

**Comment by kjmartens** [comment]
Hi @lukehmu, the tricky thing here is that we intentionally render Twig Markup and HTML in labels, etc. This allows for customers to add styling to options or even add icons, etc. Because of this, it's interfering with you trying to use `"`. If we change this behavior, it will affect other customers as well, so what we're thinking about doing is creating a setting to enable/disable HTML rendering. I've added this to the Feature Requests list and we'll likely revisit this in the next month. :)

Until then, you'll need to use the alternate character. Sorry :/
