### ISSUE TITLE
 Email "" does not comply with addr-spec of RFC 2822. 

### ISSUE THREAD

**Issue by jestov** [solspace/craft3-freeform#572]
Hi,

I recently upgraded freeform version from 3.11.11.1 to 4.0.8, after an upgrade from craft 3 to craft 4.

Days later these logs began to appear:

`
 Email "" does not comply with addr-spec of RFC 2822. {"template":"distributedEmail","file":"/var/www/html/vendor/symfony/mime/Address.php"} []`

Despite this, the submission of the forms works without a problem, but I would like to find out more about this log, does anyone have information about it?

**Comment by kjmartens** [comment]
Hi @jestov! Sorry for the trouble you're experiencing.

It's likely due to a syntax issue or similar. Can you double-check that your `distributedEmail` email notification template is not attempting to load any field names that don't exist (e.g. `email` when the actual handle is `emailAddress`, etc) or that there are no empty spaces or some other incorrect value inside the From Email / Reply-to / CC / BCC settings? 🙂 

If you cannot see any issues, can share with me what your `distributedEmail` email notification template looks like? (copy/paste the code for it or include screenshots of it in the control panel)
