### ISSUE TITLE
Textarea encoding issue

### ISSUE THREAD

**Issue by TLM-Mikael** [solspace/craft3-freeform#73]
Hi.

I have an issue with the textarea field. Basically, I use the plugin to allow my client to edit submissions and add notes in the CP. We are writing in french, so special characters are really important. 

It seems there's an encoding bug with the textarea field. If, for example, I write: 
`Test d'un texte`

It will save like this and show like this in the edit submission page:
`Test d&amp;#039;un texte`

This issue doesn't seem to appear with a normal text field. Is there a way for me to fix this? 

Thank you.

**Comment by kjmartens** [comment]
Thanks for reporting this @TLM-Mikael. I can duplicate this in my testing as well. We'll get a fix for this shortly. :)

**Comment by TLM-Mikael** [comment]
Ok! Thank you so much.

**Comment by gustavs-gutmanis** [comment]
@TLM-Mikael if it's a very pressing matter - while you're waiting on the release, you could use the `dev` branch for the time being to have this fix in your Freeform install.  
By having this line in your requirements in `composer.json` - `"solspace/craft3-freeform": "dev-dev"`  
Currently that is the only change in the `dev` branch, since we're working on `v3.10`.

**Comment by TLM-Mikael** [comment]
Thank you! It is working. :)

**Comment by kjmartens** [comment]
This is now fixed in Freeform 3.9.10 :)
