### ISSUE TITLE
Dynamic form notifications - template path param looks for html files but not twig files

### ISSUE THREAD

**Issue by piotrpog** [solspace/craft3-freeform#89]
When with Twig, using `include` tag we include file without extension, systems looks for `.twig` and `.html` file by default.

With freeform dynamic notification, with `template` param, system looks for only `html` files when we enter file path without extension. To load twig file, we have to set `twig` extension explicitly.

```
dynamicNotification: { 
	recipients: 'some@email.com',
	template: 'form_contact.twig'
}
```

**Comment by kjmartens** [comment]
This is expected behavior and not a bug. Loading a Freeform email notification template is not exactly the same as using an `include` tag, and it's further complicated due to the fact that Freeform offers both database and file options for storage. When specifying a database-based template, you would use the handle, e.g. `mytemplate`. When using file-based templates, you need to specify the complete file name including the file extension, e.g. `mytemplate.twig`.

You can read more about this in the docs here: 
https://docs.solspace.com/craft/freeform/v3/template-functions/freeform.form.html#param-dynamicnotification

>`dynamicNotification: { recipients: ["admin@example.com", "support@example.com"], template: "test.html" }`
>- Allows using a dynamic template level notification for a more fine-grained control.
>- Hard code values or pass a value from another element such as an Entry.
>- For Database entry based templates, specify the handle for template.
>- For Twig file based templates, specify the full file name including .html for template.

We may change this behavior in the future to work similarly to what you describe, but only in a major release (to protect legacy) and after we have removed the database-based template approach (you'll see how we do that in Freeform 3.11). 🙂

**Comment by piotrpog** [comment]
Thanks for info!
