### ISSUE TITLE
V5 Upgrade

### ISSUE THREAD

**Issue by StuartMcD** [solspace/craft3-freeform#982]
OK, as FF powers a lot of functionality on my site - I chose to upgrade to the latest and the start has been less then stellar. 
The templating language, behaviours and website docs have all been overhauled to be almost a new language based on the previous few years but my choice.

Templates, pfft, whatever I'll make do but when editing a form, greeted with:
![image](https://github.com/solspace/craft-freeform/assets/5855813/ec2300d3-5ef3-4e77-9bb0-884d60451191)

**Steps to reproduce**

1. Load any form
2. See error

**Expected behavior**
1. Load any form
2. Add new field

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.0
- Freeform Version: Pro 
- Freeform Edition: 5.0.1
- Fresh Install or Upgrade: Upgrade

**Additional context**
Updates done local on ddev environment, php 8.0.30

**Comment by gustavs-gutmanis** [comment]
Sorry for the inconvenience @StuartMcD

This issue has been fixed in the branch `fix/SFT-843`, and it will be released as a fix later today.
Meanwhile, to mitigate this issue for you immediately, you could temporarily set your `composer.json` Freeform version to use the branch that has the fix, by setting it to use `"solspace/craft-freeform": "dev-fix/SFT-843",`

**Comment by StuartMcD** [comment]
Figured you guys would be all over it. I'm done for today here in Aus, thx for the update and will check back later 👍

**Comment by kjmartens** [comment]
This is now fixed in Freeform 5.0.2+. 🙂
