### ISSUE TITLE
V5 Upgrade Recaptcha

### ISSUE THREAD

**Issue by StuartMcD** [solspace/craft3-freeform#983]
Another wholesale change between 4-5 - add same variables ff_captchya_key + ff_captchya_secret vars to new integration. 

![image](https://github.com/solspace/craft-freeform/assets/5855813/2b9835fd-e92a-40e0-8d94-fd972f2c8ef8)

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.0
- Freeform Version: Pro
- Freeform Edition: 5.0.1
- Fresh Install or Upgrade: Upgrade

DDEV install, Crftcms dev mode enabled

**Comment by gustavs-gutmanis** [comment]
Hi @StuartMcD 

Sorry you're running into this issue.
Could you please tell me when this issue happens? Is this in the control panel, or on the front-end?

Could you please let me know which PHP version you're on?

And could you elaborate a bit on the two variables you mentioned? Where do you need them?

**Comment by gustavs-gutmanis** [comment]
Sorry for the inconvenience @StuartMcD

This issue has been fixed in the branch `fix/SFT-843`, and it will be released as a fix later today.
Meanwhile, to mitigate this issue for you immediately, you could temporarily set your `composer.json` Freeform version to use the branch that has the fix, by setting it to use `"solspace/craft-freeform": "dev-fix/SFT-843",`

**Comment by kjmartens** [comment]
This is now fixed in Freeform 5.0.2+. 🙂
